//@version=6
// Author: Psyll.com
// Email: info@psyll.com
// Website: https://psyll.com
// Copyright: Copyright © 2025 psyll.com. All rights reserved.
indicator('Grid Bot [Grid range plugin] Predictive Ranges [psyll]', overlay = false)
settings_group = '##### Settings'
length = input.int(200, 'Length', minval = 2, group = settings_group, display = display.none)
mult = input.float(12., 'Factor', minval = 0, step = .5, group = settings_group, display = display.none)
src = input(close, 'Source', group = settings_group, display = display.none)
level = input.int(2, title = 'Level', minval = 1, maxval = 2, group = settings_group, display = display.none)
offset = input.float(1, 'Offset', group = settings_group, display = display.none)
smooth = input.int(defval = 2, title = 'Smoothness', group = settings_group, display = display.none)
width_min = input.float(0, 'Min width', group = settings_group, display = display.none)
width_max = input.float(99999, 'Max width', group = settings_group, display = display.none)
width_min_half = width_min / 2
width_max_half = width_max / 2
tf_group = '##### Timeframe'
tf_confirmation_wait = input.bool(defval = true, title = 'Wait for confirm', group = tf_group, inline = tf_group, display = display.none)
tf_no_repaint_security = input.bool(defval = true, title = 'No repaint', group = tf_group, inline = tf_group, display = display.none)
tf_barmerge_lookahead = input.bool(defval = false, title = 'Lookahead', group = tf_group, inline = tf_group, display = display.none)
tf_barmerge_gaps = input.bool(defval = false, title = 'Gaps', group = tf_group, inline = tf_group, display = display.none)
tf_type = input.string(title = 'Type', options = ['Static', 'Custom'], defval = 'Static', group = tf_group, display = display.none)
tf_static = input.timeframe(defval = '', title = 'Static', group = tf_group, display = display.none)
tf_custom = str.tostring(input.int(1, 'Custom', group = tf_group, display = display.none))
tf_type_value = switch tf_type
    'Static' => tf_static
    'Custom' => tf_custom
tf_security(source) =>
    request.security(syminfo.tickerid, tf_type_value, tf_no_repaint_security ? source[barstate.isrealtime ? 1 : 0] : source, gaps = tf_barmerge_gaps ? barmerge.gaps_on : barmerge.gaps_off, lookahead = tf_barmerge_lookahead ? barmerge.lookahead_on : barmerge.lookahead_off)[tf_no_repaint_security ? barstate.isrealtime ? 0 : 1 : 0]
display_group = '##### Display'
price_color = input.color(color.black, 'Candles color', display = display.none, group = display_group)
plotcandle(open, high, low, close, color = price_color, bordercolor = price_color, wickcolor = price_color, display = display.pane)
grid_high = 0.0
grid_low = 0.0
ranges(length, mult) =>
    var avg = src
    var hold_atr = 0.
    atr = nz(tf_security(ta.atr(length))) * mult
    avg := src - avg > atr ? avg + atr : avg - src > atr ? avg - atr : avg
    hold_atr := avg != avg[1] ? atr / 2 : hold_atr
    [avg + hold_atr * 2, avg + hold_atr, avg, avg - hold_atr, avg - hold_atr * 2]
[prR2, prR1, avg, prS1, prS2] = ranges(length, mult)
if level == 1
    grid_high := prR1 + offset
    grid_low := prS1 - offset
    grid_low
if level == 2
    grid_high := prR2 + offset
    grid_low := prS2 - offset
    grid_low
grid_middle = (grid_high + grid_low) / 2
if grid_high - grid_low < width_min
    grid_high := grid_middle + width_min_half
    grid_low := grid_middle - width_min_half
    grid_low
if grid_high - grid_low > width_max
    grid_high := grid_middle - width_max_half
    grid_low := grid_middle + width_max_half
    grid_low
grid_middle := ta.sma(grid_middle, smooth)
grid_high := ta.sma(grid_high, smooth)
grid_low := ta.sma(grid_low, smooth)
plot(grid_high, 'High', color.green, display = display.all)
plot(grid_middle, 'Middle', color.silver, display = display.pane)
plot(grid_low, 'Low', color.red, display = display.all)
