//@version=6
// Author: Psyll.com
// Email: info@psyll.com
// Website: https://psyll.com
// Copyright: Copyright © 2025 psyll.com. All rights reserved.

indicator('Grid Bot [Grid range plugin] RSI Channel [psyll]', overlay = false)
decimal_places = 0
tick_size = syminfo.mintick
while tick_size < 1
    tick_size := tick_size * 10
    decimal_places := decimal_places + 1
    decimal_places
settings_group = 'Settings #################################################'
rsi_channel_src = input(close, title = 'Source', group = settings_group, display = display.none)
rsi_channel_len = input(14, title = 'Length', group = settings_group, display = display.none)
rsi_channel_oblevel = input.int(70, title = 'OB Level', maxval = 99, minval = 1, group = settings_group, display = display.none)
rsi_channel_oslevel = input.int(30, title = 'OS Level', maxval = 99, minval = 1, group = settings_group, display = display.none)
rsi_channel_smt = input.int(1, title = 'EMA Smoothing', minval = 1, group = settings_group, display = display.none)
rsi_channel_offset = input.float(1, 'Offset', group = settings_group, display = display.none)
smooth = input.int(1, 'Smoothness', minval = 1, group = settings_group, display = display.none)
width_min = input.float(0, 'Min width', group = settings_group, display = display.none)
width_max = input.float(99999, 'Max width', group = settings_group, display = display.none)
width_min_half = width_min / 2
width_max_half = width_max / 2
tf_group = 'Timeframe ###############################################'
tf_confirmation_wait = input.bool(defval = true, title = 'Wait for confirm', group = tf_group, inline = tf_group, display = display.none)
tf_no_repaint_security = input.bool(defval = true, title = 'No repaint', group = tf_group, inline = tf_group, display = display.none)
tf_barmerge_lookahead = input.bool(defval = false, title = 'Lookahead', group = tf_group, inline = tf_group, display = display.none)
tf_barmerge_gaps = input.bool(defval = false, title = 'Gaps', group = tf_group, inline = tf_group, display = display.none)
tf_type = input.string(title = 'Type', options = ['Static', 'Custom'], defval = 'Static', group = tf_group, display = display.none)
tf_static = input.timeframe(defval = '', title = 'Static', group = tf_group, display = display.none)
tf_custom = str.tostring(input.int(1, 'Custom', group = tf_group, display = display.none))
tf_type_value = switch tf_type
    'Static' => tf_static
    'Custom' => tf_custom
tf_security(source) =>
    request.security(syminfo.tickerid, tf_type_value, tf_no_repaint_security ? source[barstate.isrealtime ? 1 : 0] : source, gaps = tf_barmerge_gaps ? barmerge.gaps_on : barmerge.gaps_off, lookahead = tf_barmerge_lookahead ? barmerge.lookahead_on : barmerge.lookahead_off)[tf_no_repaint_security ? barstate.isrealtime ? 0 : 1 : 0]
display_group = 'Display ##################################################'
price_color = input.color(color.black, 'Candles color', display = display.none, group = display_group)
plotcandle(open, high, low, close, color = price_color, bordercolor = price_color, wickcolor = price_color, display = display.pane)
rsi_channel_src := tf_security(rsi_channel_src)
my_rsi(x, len) =>
    u = math.max(x - x[1], 0)
    d = math.max(x[1] - x, 0)
    sumu = 0.0
    sumd = 0.0
    sumu := (u + (len - 1) * nz(sumu[1])) / rsi_channel_len
    sumd := (d + (len - 1) * nz(sumd[1])) / rsi_channel_len
    rs = sumu / sumd
    res = 100 - 100 / (1 + rs)
    [res, sumu, sumd]
[Rsi, sumu, sumd] = my_rsi(rsi_channel_src, rsi_channel_len)
diffupob = sumd * (100 / (100 - rsi_channel_oblevel) - 1) * rsi_channel_len - (rsi_channel_len - 1) * nz(sumu[1])
diffdnob = sumu / (100 / (100 - rsi_channel_oblevel) - 1) * rsi_channel_len - (rsi_channel_len - 1) * nz(sumd[1])
diffupos = sumd * (100 / (100 - rsi_channel_oslevel) - 1) * rsi_channel_len - (rsi_channel_len - 1) * nz(sumu[1])
diffdnos = sumu / (100 / (100 - rsi_channel_oslevel) - 1) * rsi_channel_len - (rsi_channel_len - 1) * nz(sumd[1])
oblev = Rsi <= rsi_channel_oblevel ? rsi_channel_src + diffupob : rsi_channel_src - diffdnob
oslev = Rsi <= rsi_channel_oslevel ? rsi_channel_src + diffupos : rsi_channel_src - diffdnos
oblev := tf_security(ta.ema(oblev, rsi_channel_smt))
oslev := tf_security(ta.ema(oslev, rsi_channel_smt))
grid_high = oblev + rsi_channel_offset
grid_low = oslev - rsi_channel_offset
grid_middle = (grid_high + grid_low) / 2
if grid_high - grid_low < width_min
    grid_high := grid_middle + width_min_half
    grid_low := grid_middle - width_min_half
    grid_low
if grid_high - grid_low > width_max
    grid_high := grid_middle - width_max_half
    grid_low := grid_middle + width_max_half
    grid_low
grid_high := ta.sma(grid_high, smooth)
grid_middle := ta.sma(grid_middle, smooth)
grid_low := ta.sma(grid_low, smooth)
// Plots
plot(grid_high, 'High', color.green, display = display.all)
plot(grid_middle, 'Middle', color.silver, display = display.pane)
plot(grid_low, 'Low', color.red, display = display.all)
